after "$ git grep -n 'new Exception(' | grep -v tests | cut -d: -f1,2"

pull closed [25698](https://github.com/dotnet/corefx/pull/25698) no action on this namespace after discussion
```csharp
src/System.Data.SqlClient/src/System/Data/Sql/SqlNorm.cs:104
src/System.Data.SqlClient/src/System/Data/Sql/SqlNorm.cs:246
src/System.Data.SqlClient/src/System/Data/Sql/SqlSer.cs:199
src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SSRP.cs:37
src/System.Data.SqlClient/src/System/Data/SqlClient/SqlUtil.cs:197
```
No action
```csharp
src/Microsoft.Diagnostics.Tracing.EventSource.Redist/shared/StubEnvironment.cs:69 --> Assert code #IF ES_BUILD_AGAINST_DOTNET_V35
src/System.Drawing.Common/src/System/Drawing/Font.Serializable.cs:83 --> excluded from compilation
src/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:556 --> internal no references found
src/System.Management/src/System/Management/WMIGenerator.cs:566 --> comment out
src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.CurlResponseMessage.cs:58  --> sentinel object
src/System.Net.Mail/src/System/Net/Mail/MailHeaderInfo.cs:79 --> #if DEBUG
src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.WinRT.cs:49 --> rethrow WebSocketException()
src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DiagnosticUtility.cs:78  --> it seems like never bubble out to user, no useful test found, maybe on race condition bug or OutOfMemoryException, StackOverflowException
src/System.Private.Xml/src/System/Xml/BinaryXml/XmlBinaryReader.cs:3217 --> #if DEBUG 
src/System.Private.Xml/src/System/Xml/BinaryXml/XmlBinaryReader.cs:3219 --> #if DEBUG
src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriter.cs:1934 --> comment out
src/System.Runtime.Caching/src/System/Runtime/Caching/Dbg.cs:867 --> #IF DEBUG 
src/System.Runtime.WindowsRuntime/src/System/Runtime/InteropServices/WindowsRuntime/WindowsRuntimeBuffer.cs:93 --> rethrow NotImplementedException()
src/System.Runtime.WindowsRuntime/src/System/Threading/Tasks/TaskToAsyncInfoAdapter.cs:982 --> "instead of failing with an inexplicable NullReferenceException"
src/System.Threading.Channels/src/System/Threading/Channels/ChannelUtilities.cs:15 --> Sentinel object used to indicate being done writing.
```

@karelz @danmosemsft i think we can close this issue.
Maybe the [guideline](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types#exception-and-systemexception) should be:
"X DO NOT throw System.Exception or System.SystemException if exception can reach user code." or something like that.
In my journey i found some place where the exception is throw and catch internally.
In other place throw generic exception is used because there isn't a good one already present and no custom class is used. 

